services:
  api:
    build: ./api
    ports:
      - "5573:5573"
    environment:
      - NODE_ENV=development
      - PORT=5573
    volumes:
      - ./api:/app
      - /app/node_modules
      - ./api/public/uploads:/app/public/uploads
    networks:
      - extension-network
    env_file:
      - ./api/.env

  dashboard:
    build: ./dashboard
    ports:
      - "3682:3682"
    volumes:
      - ./dashboard:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - extension-network
    env_file:
      - ./dashboard/.env

networks:
  extension-network:
    driver: bridge
