services:
  api:
    build: ./api
    ports:
      - "5573:5573"
    environment:
      - NODE_ENV=production
      - PORT=5573
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ./api:/app
      - /app/node_modules
      - ./api/public/uploads:/app/public/uploads
    depends_on:
      - mongo
    networks:
      - extension-network
    env_file:
      - ./api/.env

  dashboard:
    build: ./dashboard
    ports:
      - "3682:3682"
    volumes:
      - ./dashboard:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - extension-network
    env_file:
      - ./dashboard/.env

  mongo:
    image: mongo:latest
    ports:
      - "0.0.0.0:27017:27017" # Accessible from anywhere
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-extension}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-Password1234}
    command: mongod --bind_ip_all
    volumes:
      - mongo-data:/data/db
    networks:
      - extension-network

networks:
  extension-network:
    driver: bridge

volumes:
  mongo-data:
